[package]
name = "revparse"
version = "0.1.2"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
keywords = ["argument-parser", "gnu", "flags", "options", "subcommands"]
description = "GNU Argument Parser, that's easy to use."
repository = "https://github.com/revellan/revparse"
readme = "README.md"


[dependencies]
