[package]
name = "revparse"
version = "1.2.1"
edition = "2024"
license = "MIT"
keywords = ["argument-parser", "gnu", "flags", "options", "subcommands"]
description = "GNU Style Argument Parser, that's easy to use."
repository = "https://github.com/revellan/revparse"
homepage = "revparse.revellan.com"
readme = "README.md"


[dependencies]
