[package]
name = "revparse"
version = "1.2.4"
edition = "2024"
license = "MIT"
keywords = ["argument", "parser", "flags", "clap", "argparse"]
description = "GNU Style Argument Parser, that's easy to use."
repository = "https://github.com/revellan/revparse"
homepage = "https://revparse.revellan.com"
readme = "README.md"

[dependencies]
